services:
  - type: web
    name: mochi-chatbot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "chainlit run app.py -w"
    envVars:
      - key: HF_API_KEY
        sync: false
