services:
  - type: web
    name: mochi-chatbot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "chainlit run app.py -h 0.0.0.0 -p $PORT"
    envVars:
      - key: HF_API_KEY
        sync: false
